### ISSUE TITLE
【bug】插件转markdown出现内容丢失

### ISSUE THREAD

**Issue by ShellMonster** [sailist/chatgpt-markdown-extension#1]
**背景：**
ChatGPT回复长文时，可能出现markdown无法转换的情况。

**以下为原文和转markdown效果：**
<img width="687" alt="image" src="https://user-images.githubusercontent.com/25876140/231426336-01b4041f-3aaf-4974-bd43-225d58413bb1.png">
![image](https://user-images.githubusercontent.com/25876140/231426586-d38c3fcc-9a17-4c51-bd37-291954468111.png)

**备注：**
多次刷新网页后，再次点击markdown按钮，可全文转换。
<img width="709" alt="image" src="https://user-images.githubusercontent.com/25876140/231426415-40e38dec-2a30-46fe-aea9-0798cfbd89f0.png">

**Comment by sailist** [comment]
想问以下使用版本呢？最新版本（1.2.1）做了识别优化，会在回复完全结束后才生成上方按钮并进行转换，应该不存在这个问题

<img width="846" alt="CleanShot 2023-04-12 at 18 57 17@2x" src="https://user-images.githubusercontent.com/25661058/231437599-5fde46ab-ee78-4d81-a37a-2a419f8c5729.png">

**Comment by ShellMonster** [comment]
> 想问以下使用版本呢？最新版本（1.2.1）做了识别优化，会在回复完全结束后才生成上方按钮并进行转换，应该不存在这个问题
> 
> <img alt="CleanShot 2023-04-12 at 18 57 17@2x" width="846" src="https://user-images.githubusercontent.com/25661058/231437599-5fde46ab-ee78-4d81-a37a-2a419f8c5729.png">

版本忘说了，V1.2.1，我clone源码然后编译的；使用文件夹的方式加载进chrome里面；chrome版本最新112.0.5615.49(arm64)；

你可以试试“请你基于xxx帮我写一篇不低于500字的新闻”这种提示词看看，内容特别长；

**Comment by sailist** [comment]
好的，我这边还是无法成功复现，不过我之后会重新推一个版本，修改按下按钮时的行为是重新渲染而不是使用之前的渲染结果，应该就可以解决这个问题

**Comment by sailist** [comment]
辛苦试一下，如果可以的话请告知

**Comment by ShellMonster** [comment]
> 

V1.2.1版，可以试试这个提示内容；
提示文本：
> 你是一个技术领域的专家，请你讲一下什么是数据结构，内容要详细，不低于500字内容；

![缺陷](https://user-images.githubusercontent.com/25876140/231619537-c715eab8-e84e-49aa-978f-5e41d7b32487.gif)

**Comment by sailist** [comment]
仍然无法复现。。可能是回复超出字数上限时的回复结束行为和我的定义的存在一些差别，你用最新的 commit 仍然会出现该问题吗

**Comment by sailist** [comment]
可以加q群 239763240 沟通

**Comment by ShellMonster** [comment]
> 可以加q群 239763240 沟通

刚刚测试了最新的commit，同样的文字没有复现；
昨天出现bug的是昨天下午15点30左右下载的1.2.1的`Source code(zip)`编译的。
