### ISSUE TITLE
按照安装步骤一直报错: 清单文件缺失或不可读取

### ISSUE THREAD

**Issue by wolfdan666** [sailist/chatgpt-markdown-extension#2]
未能成功加载扩展程序
文件
~\code\chatgpt-markdown-extension\dist
错误
清单文件缺失或不可读取
无法加载清单。

ChatGPT说需要  “manifest.json”的清单文件 ， 但是只看到   manifest.ts  ，是需要其他操作吗

**Comment by sailist** [comment]
可以直接下载 dist.crx 文件拖到 Chrome 扩展程序的 tab 页里，如果是从文件加载的话，需要手动编译 `npm install && npm run build` 然后加载 `./dist`文件夹的内容

**Comment by wolfdan666** [comment]
之前试过了，直接拖进去一直无法绕过Chrome报错：  `该扩展程序未列在 Chrome 应用商店中，并可能是在您不知情的情况下添加的`  。**从而导致无法启用插件** 。

所以我以为找到 manifest.json 能绕过，就问了这个问题，如果手动编译也无法绕过这个 Chrome 的，只能等 应用上架了。

**Comment by lifesign** [comment]
dist.crx 我下载完貌似被自动清理了，而且会有这个提示，建议是不是改个名字
![image](https://user-images.githubusercontent.com/2189610/232049239-aec3d364-058f-41b1-9c7b-575deaf42656.png)

**Comment by sailist** [comment]
> dist.crx 我下载完貌似被自动清理了，而且会有这个提示，建议是不是改个名字 ![image](https://user-images.githubusercontent.com/2189610/232049239-aec3d364-058f-41b1-9c7b-575deaf42656.png)

新上传了 [dist.crx.bak](https://github.com/sailist/chatgpt-enhancement-extension/releases/download/v1.3.0/dist.crx.bak)，试试看呢

**Comment by sailist** [comment]
> 之前试过了，直接拖进去一直无法绕过Chrome报错： `该扩展程序未列在 Chrome 应用商店中，并可能是在您不知情的情况下添加的` 。**从而导致无法启用插件** 。
> 
> 所以我以为找到 manifest.json 能绕过，就问了这个问题，如果手动编译也无法绕过这个 Chrome 的，只能等 应用上架了。

今天发现我的 build 参数有问题，编译后 manifest.ts 可能没有被正确的解析到 dist 文件下的 manifest.json 文件，刚刚改了一下，如果有条件且愿意的话麻烦再试一下，并确保编译（npm run build）后 dist 文件夹下有 manifest.json 文件
