### ISSUE TITLE
扩展程序无法启用，安装即是禁用暂停

### ISSUE THREAD

**Issue by XZ1314XZ** [sailist/chatgpt-markdown-extension#4]
该扩展程序未列在 Chrome 应用商店中，并可能是在您不知情的情况下添加的。

![Snipaste_2023-04-16_00-26-03](https://i2.100024.xyz/2023/04/16/fkv9o.webp)

**Comment by sailist** [comment]
这个是 chrome 浏览器对非开发者做出的安全限制，您可以参考以下内容尝试进行解决
 - https://blog.csdn.net/qq_40808344/article/details/82728644
 - https://blog.berd.moe/archives/add-third-app-to-chrome/

**Comment by zhy0235** [comment]
第一种方法不行。第二种方法首先只有windows，其次电脑小白不会。

**Comment by XZ1314XZ** [comment]
谢谢，通过方法2已成功解决。需要注意的是和教程贴部分名称有些许不同，但步骤仍然一致。

![iE1KMo.png](https://i.328888.xyz/2023/04/17/iE1KMo.png)

**Comment by Mrered** [comment]
<img width="872" alt="image" src="https://github.com/sailist/chatgpt-enhancement-extension/assets/34948506/17042985-da6f-49b6-9f08-14cdb054acf6">
<img width="494" alt="image" src="https://github.com/sailist/chatgpt-enhancement-extension/assets/34948506/a32701bc-28aa-4e17-a724-e4fb687b2ee3">
<img width="494" alt="image" src="https://github.com/sailist/chatgpt-enhancement-extension/assets/34948506/0b55d81f-a3e2-4a4a-8b5f-cab67ea9c536">
无法使用。。。
