### ISSUE TITLE
新增的regex prompts刷新后会消失

### ISSUE THREAD

**Issue by fan1jun** [sailist/chatgpt-markdown-extension#5]
如题，新增regex prompt在设置页中刷新后会消失，且在chatgpt页面使用时常常也会消失或显示不正常

**Comment by sailist** [comment]
可不可以描述清楚版本？默认值会在有新增项后删除，已经设置好的值在使用页面需要刷新才能显示，如果是这两个行为之外的话，麻烦提供一下可复现实例或者操作
