### ISSUE TITLE
是否可以增加regex prompt的终止标记

### ISSUE THREAD

**Issue by fan1jun** [sailist/chatgpt-markdown-extension#6]
增加regex prompt的终止标记可使PDF的阅读更加高效

**Comment by sailist** [comment]
终止标记是什么，$？可以具体描述一下期望行为吗

**Comment by sailist** [comment]
我一直也没有想好怎么进一步细化拖入 PDF 后的行为，所以现在只能是一页一页的读，有更好的想法的话，欢迎分享~

**Comment by draftman9** [comment]
> 我一直也没有想好怎么进一步细化拖入 PDF 后的行为，所以现在只能是一页一页的读，有更好的想法的话，欢迎分享~

1. 或许可以先设定好让它只接收信息，由于有字数限制，我们一页一页地发，只让它回”收到“。
2. 发完后，告知它我已经发完了。
3. 问问题：请帮我总结下这篇文章写了什么，每段写一个小总结，创新点什么之类的问题，让它慢慢回，一段一段回。如果有公式，可以让它写下伪代码。
 
这样它回复时应该可以将全文都考虑在内了，问题也比较普适。
