### ISSUE TITLE
Mac 英文系统下乱码

### ISSUE THREAD

**Issue by leeronzhang** [sailist/chatgpt-markdown-extension#7]
不知道为何，Extension的设置打开是乱码。很好奇里面内容
![Screenshot 2023-04-17 at 09.05.06.png](https://pic.peo.pw/a/2023/04/17/643c9ba5d3300.png)

**Comment by sailist** [comment]
Chrome 插件商店的目前版本有些低，当时option页面莫名其妙的存在编码问题，目前新版本还在审核，该问题已经解决了，如果不是从 Github 安装的话，麻烦四五天左右后从商店更新一下版本（1.3.0），就不会有编码问题了。

> 内容是一串测试用的 Prompt，在那个版本中没有实际用到
